### PR TITLE
Explain full paths for LEDs

### PR DESCRIPTION
**Pull request by melroy89**
Missing `/sys/class/` to the path.. I needed to search a bit where the leds where, but I think it's better to write out the full path.

### CODE REVIEW

**Comment by gotzl** [comment]
Well, there are couple of places in the sysfs were you can find the leds :)
I think the most canonical place to look at is the same place were all the other wheel related files are located, namely `/sys/module/hid_fanatec/drivers/hid:fanatec/0003:0EB7:<PID>.*/`, which is already mentioned in the readme.

**Comment by melroy89** [comment]
OK but this line `leds/0003:0EB7:0005.*::RPMx/brightness` in the readme is currently very unclear where to look. We can try to explain there are multiple places, but just saying `leds/` isn't sufficient.. I was searching a lot 😆

**Comment by melroy89** [comment]
OK. I updated the PR, have a look again 👍🏽 ..

**Comment by gotzl** [comment]
I mean, all sysfs paths mentioned in this section are relative to the path mentioned at the top of the section. Now why be this explicit in case of the LEDs, but not in case of all the other files?

**Pull request closed without merging**
