### PR TITLE
Clubsport v2 support

### PR DESCRIPTION
**Pull request by mkoreneff**
add support for Fanatec_FANATEC_ClubSport_Wheel_Base_V2

### CODE REVIEW

**Comment by gotzl** [comment]
Thanks for your contribution! It it working with clubsport v2? I was hoping that fanatec uses one protocol for their but I only have the csl elite ...

**Comment by gotzl** [comment]
Thanks for your contribution!
Is it working with the clubsport? I was hoping that fanatec would use the same protocol for their wheel bases...

**Comment by mkoreneff** [comment]
Yeah works really well after I added the correct id for my device. Got nice
ffb in project cars 2, took me a little bit to figure it out though.

Thanks for your help and for the driver!

**Comment by mkoreneff** [comment]
My CSL Elite PS4 wheelbase is being reported as Fanatec_FANATEC_ClubSport_Wheel_Base_V2 by the kernel. Have updated the readme

**Comment by gotzl** [comment]
So, you in fact have a CSL Elite, not the ClubSport? Do you have a `Mode` button? Does it have an effect how the wheel base is registered by the kernel?

**Comment by mkoreneff** [comment]
This is the unit I have -
https://fanatec.com/eu-en/bundles/csl-elite-ps4-starter-kit

The mode button does change the way the wheelset is detected, and the
axis/buttons exposed as viewed by jstest-gtk.
The 4 modes I can select are: Xbox (Red), PS4 (Blue), PC (Yellow/Orange)
and ??? (Purple). I have been using PC mode.
I will confirm tomorrow what the device ID's are for each mode.


Thanks,

Mike
www.ironmikemusing.com

**Comment by mkoreneff** [comment]
FWIW I saw this on [reddit buyers guide](https://www.reddit.com/r/simracing/wiki/buyingguide):

_Fanatec Clubsport V2.5 - Fanatec's former flagship wheelbase. To give you an idea of where this wheelbase stands compared to the CSL Elite, the "CSL" actually stands for "Clubsport Lite," whereas this is the "Clubsport" (V2.5) wheelbase._

**Comment by gotzl** [comment]
Interesting ;) So, I've the same model and I played around with the modes. I get:

* red (short press): ftec_csl_elite 0003:0EB7:0005.00AC: input,hiddev0,hidraw8: USB HID v1.11 Joystick [Fanatec FANATEC CSL Elite Wheel Base PlayStation 4] on usb-0000:00:14.0-4.1/input0
* blue (short press): hid-generic 0003:0EB7:0E04.00AD: input,hiddev0,hidraw8: USB HID v1.11 Gamepad [Fanatec FANATEC CSL Elite Wheel Base PlayStation 4] on usb-0000:00:14.0-4.1/input0
* orange (long press): hid-generic 0003:0EB7:0001.00AE: input,hidraw8: USB HID v1.11 Joystick [Fanatec FANATEC ClubSport Wheel Base V2] on usb-0000:00:14.0-4.1/input0
* purple (long press): hid-generic 0003:046D:C260.00AF: input,hiddev0,hidraw8: USB HID v1.10 Joystick [Fanatec] on usb-0000:00:14.0-4.1/input0

So, I guess you had your wheel in 'orange' mode? Is there any reason for this? I think the 'default' mode is red. This is the one I use, anyhow...

**Comment by mkoreneff** [comment]
I had some problems in the beginning trying to calibrate the wheel in red
or blue mode with Project CARS 2. I read somewhere that orange mode is PC,
so I chose orange mode.

I can confirm I see the same modes/ID as you.
red - ftec_csl_elite 0003:0EB7:0005.002A: input,hiddev4,hidraw8: USB HID
v1.11 Joystick [Fanatec FANATEC CSL Elite Wheel Base PlayStation 4] on
usb-0000:00:14.0-6/input0
blue - hid-generic 0003:0EB7:0E04.002B: input,hiddev4,hidraw8: USB HID
v1.11 Gamepad [Fanatec FANATEC CSL Elite Wheel Base PlayStation 4] on
usb-0000:00:14.0-6/input0
orange (i added support for this mode) -  ftec_csl_elite
0003:0EB7:0001.002C: input,hidraw8: USB HID v1.11 Joystick [Fanatec FANATEC
ClubSport Wheel Base V2] on usb-0000:00:14.0-6/input0
purple- hid-generic 0003:046D:C260.002D: input,hiddev4,hidraw8: USB HID
v1.10 Joystick [Fanatec] on usb-0000:00:14.0-6/input0

**Comment by mcoffin** [comment]
I added the ClubSport v2.5 wheelbase (id: `0004`) to this, and it's working for me as well, with one big caveat.

The centering force that is on by default seems to not be able to be disabled, so conflicts with FFB from (at least) ACC. If someone could help me get that disabled, it would be *perfect*.

**Comment by gotzl** [comment]
@mcoffin so you do have an actual ClubSport v2.5 or is there another compatibility mode?
Can you adjust the setting via the tuning menu of the wheel itself?
I've already extracted some commands to modify springs etc of the CSL, maybe they fit the ClubSport as well... Can you test what I've pushed to the cs-v25 branch?

**Comment by mcoffin** [comment]
Will do. It IS the real ClubSport v2.5, AMD the only available modes were Xbox (Green light),and PC (red light). Adjusting SPRING to off in the wheel tuning menu did nothing. It’s almost as if it’s just missing a command sent by the driver on startup.

I’ll try the above branch, and get back to you either way. More than happy to provide dumps from Windows as well, though I’ve never used wireshark for USB before.

Thanks for the snappy reply.

**Pull request merged**
